# A Single Neuron

In [1]:
import numpy as np
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2
output = np.dot(inputs,weights)+bias 
output

4.8

# A Layer of Neurons with Numpy

In [2]:
import numpy as np
inputs = [1,2,3,2.5]
weights = [ [0.2,0.8,-0.5,1],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]
          ]
biases = [2,3,0.5]
layer_outputs = np.dot(weights,inputs)+biases
layer_outputs

array([4.8  , 1.21 , 2.385])

# A Batch of Data

In [3]:
inputs = [[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]

# Matrix Product

In [4]:
a = [1,2,3]
np.array([a])


array([[1, 2, 3]])

In [5]:
np.expand_dims(np.array(a),axis = 0)

array([[1, 2, 3]])

In [6]:
a = [1,2,3]
b = [2,3,4]
a = np.array([a])
b = np.array([b]).T
np.dot(a,b)

array([[20]])

# A Layer of Neurons & Batch of Data w/Numpy

In [7]:
inputs = [[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]
outputs = np.dot(inputs,np.array(weights).T)+biases
outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])